<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Now you can create and share posts dire_539f07</name>
   <tag></tag>
   <elementGuidId>831b3872-d0f2-4b93-8ee9-07ba3bf76c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span._2dbep.qNELH > img._6q-tv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[6]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>12fda8eb-eb96-4de5-865b-cc39715874ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>drylaaa's profile picture</value>
      <webElementGuid>10c373fe-5992-4c61-96dd-5254f6b7148c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6q-tv</value>
      <webElementGuid>f0c3f4ad-28f1-4cef-bbac-aa8d1424c366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>04883783-c030-460e-a8b1-bc2d618d29c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>user-avatar</value>
      <webElementGuid>01d92d1e-40d1-4260-b642-a0b8ae3892ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>74f35271-8029-41b5-9e2a-52c09edf2870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://instagram.fcgk18-2.fna.fbcdn.net/v/t51.2885-19/275890815_123357593392732_1685510607827226456_n.jpg?stp=dst-jpg_s150x150&amp;_nc_ht=instagram.fcgk18-2.fna.fbcdn.net&amp;_nc_cat=104&amp;_nc_ohc=ebRITZkmlCYAX-OmQL0&amp;edm=AIQHJ4wBAAAA&amp;ccb=7-4&amp;oh=00_AT9QrWzfayOY7vUS38llv3XXsT_Xa6LWbLBoStT2soLcuA&amp;oe=6289E58B&amp;_nc_sid=7b02f1</value>
      <webElementGuid>01cdca42-127c-4efd-a2c3-4b2a9346222f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-root&quot;)/section[@class=&quot;_9eogI E3X2T&quot;]/nav[@class=&quot;kqZqN x-Vyw&quot;]/div[@class=&quot;_8MQSO  Cx7Bp&quot;]/div[@class=&quot;_lz6s&quot;]/div[@class=&quot;MWDvN&quot;]/div[@class=&quot;ctQZg KtFt3&quot;]/div[@class=&quot;J5g42&quot;]/div[@class=&quot;XrOey&quot;]/div[@class=&quot;EforU&quot;]/span[@class=&quot;_2dbep qNELH&quot;]/img[@class=&quot;_6q-tv&quot;]</value>
      <webElementGuid>e25c30a7-2f80-492e-96f6-68afced845a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-root']/section/nav/div[2]/div/div/div[3]/div/div[6]/div/span/img</value>
      <webElementGuid>f161af02-2e88-41f1-8fa5-8d4c2c072a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt=&quot;drylaaa's profile picture&quot;])[2]</value>
      <webElementGuid>e08e7001-9760-4020-b689-17d3b9059ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/img</value>
      <webElementGuid>f9825d78-be37-404e-b5ad-f780d4e8c14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;drylaaa&quot; , &quot;'&quot; , &quot;s profile picture&quot;) and @src = 'https://instagram.fcgk18-2.fna.fbcdn.net/v/t51.2885-19/275890815_123357593392732_1685510607827226456_n.jpg?stp=dst-jpg_s150x150&amp;_nc_ht=instagram.fcgk18-2.fna.fbcdn.net&amp;_nc_cat=104&amp;_nc_ohc=ebRITZkmlCYAX-OmQL0&amp;edm=AIQHJ4wBAAAA&amp;ccb=7-4&amp;oh=00_AT9QrWzfayOY7vUS38llv3XXsT_Xa6LWbLBoStT2soLcuA&amp;oe=6289E58B&amp;_nc_sid=7b02f1']</value>
      <webElementGuid>75429a71-6e4a-4f2f-9063-d51ab2f316c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
