<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_123456789101112131415161718192021222_d181e2</name>
   <tag></tag>
   <elementGuidId>a049a8c4-6138-4d18-b719-313308280202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-root']/section/main/div/div/div/div/div[4]/div/div/span/span[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc411a79-90b0-4b0a-882b-697302b26df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h144Z  </value>
      <webElementGuid>0e103c23-650b-42e3-a180-d0daf363a3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hari:</value>
      <webElementGuid>45644a59-d39b-4878-a1e8-36314eead6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123456789101112131415161718192021222324252627282930</value>
      <webElementGuid>2544dd85-0f99-4ec3-9842-108ef38f1f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-root&quot;)/section[@class=&quot;_9eogI E3X2T&quot;]/main[@class=&quot;wG4fl  UDpcu&quot;]/div[@class=&quot;qF0y9          Igw0E   rBNOH          YBx95   ybXk5    vwCYk              MGky5                                                              i0EQd&quot;]/div[@class=&quot;rgFsT&quot;]/div[@class=&quot;gr27e&quot;]/div[@class=&quot;qF0y9          Igw0E   rBNOH        eGOV_       acqo5   _4EzTm                                                                                      yV-Ex       HVWg4&quot;]/div[@class=&quot;qF0y9          Igw0E     IwRSH      eGOV_       acqo5   _4EzTm    bkEs3                                                      DhRcB&quot;]/div[1]/div[@class=&quot;qF0y9          Igw0E   rBNOH        eGOV_       acqo5   _4EzTm&quot;]/span[1]/span[@class=&quot;O15Fw&quot;]/select[@class=&quot;h144Z&quot;]</value>
      <webElementGuid>bd596220-a654-4d7f-888d-0e4116cc4c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-root']/section/main/div/div/div/div/div[4]/div/div/span/span[2]/select</value>
      <webElementGuid>26f396eb-2202-4aea-9538-91d2be44c067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa saya harus memberikan tanggal lahir?'])[1]/following::select[2]</value>
      <webElementGuid>a1c85004-21ff-4075-9fde-1c6eb688f4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ini tidak akan menjadi bagian profil publik Anda.'])[1]/following::select[2]</value>
      <webElementGuid>4a7dbe5c-e878-4979-a896-2923f1351ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda harus memasukkan tanggal lahir'])[1]/preceding::select[2]</value>
      <webElementGuid>eda7c3ba-7689-4e11-a37f-8a344450c322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::select[2]</value>
      <webElementGuid>d0e33aac-dbb6-4b45-b58b-89a591c1358d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>32d046c8-6f01-49af-8f21-8f3a2e16cc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Hari:' and (text() = '123456789101112131415161718192021222324252627282930' or . = '123456789101112131415161718192021222324252627282930')]</value>
      <webElementGuid>b47dfb2d-f099-47a9-bb91-b5de2803f711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
