<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nama pengguna_coreSpriteInputError gBp1f</name>
   <tag></tag>
   <elementGuidId>011d739e-ebc3-413b-9eee-aee3666d74ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-root']/section/main/div/div/div/div[2]/form/div[5]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.coreSpriteInputError.gBp1f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06f426bc-50b7-484a-bc68-466b7e239dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coreSpriteInputError gBp1f</value>
      <webElementGuid>d2dbe06a-6431-4f4a-b357-e5c0a18d77ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-root&quot;)/section[@class=&quot;_9eogI E3X2T&quot;]/main[@class=&quot;wG4fl  UDpcu&quot;]/div[@class=&quot;qF0y9          Igw0E   rBNOH          YBx95   ybXk5    vwCYk              MGky5                                                              i0EQd&quot;]/div[@class=&quot;rgFsT&quot;]/div[@class=&quot;gr27e&quot;]/div[@class=&quot;P8adC&quot;]/form[@class=&quot;XFYOY&quot;]/div[@class=&quot;WZdjL&quot;]/div[@class=&quot;_9GP1n&quot;]/div[@class=&quot;i24fI&quot;]/span[@class=&quot;coreSpriteInputError gBp1f&quot;]</value>
      <webElementGuid>52afbe14-69ae-4526-aa50-f65a20f74172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-root']/section/main/div/div/div/div[2]/form/div[5]/div/div/span</value>
      <webElementGuid>1dfd027b-493c-4f28-acca-fb2c1da2f509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span</value>
      <webElementGuid>67e9b3b4-010b-41ff-b072-ec07c0e0e9e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
