<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tokopedia</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dff6b75f-c965-47c5-a1b4-c5fc125775a8</testSuiteGuid>
   <testCaseLink>
      <guid>687aef93-e854-409d-b498-ee2cb2d8745a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'https://www.tokopedia.com/register'</defaultValue>
         <description></description>
         <id>3e9f10d5-3a7d-4188-a86f-ee8d6cb7fdd8</id>
         <masked>false</masked>
         <name>url</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Tugas/Register Tokopedia</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e16db28d-7b73-48aa-b32e-b3ec549e2402</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Tokopedia</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e16db28d-7b73-48aa-b32e-b3ec549e2402</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>499f81ee-4388-4186-a82c-de27fcd9397d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e9f10d5-3a7d-4188-a86f-ee8d6cb7fdd8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
