<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kategori_css-15kuy91</name>
   <tag></tag>
   <elementGuidId>5ef38d43-f40f-4c7b-becf-2d3d3b95b846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.css-15kuy91</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-main-wrapper']/div[2]/div[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bd1f8bc0-a319-41d8-a171-000ec2ecf164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-15kuy91</value>
      <webElementGuid>e9bd5435-d84e-4259-a172-46797aa38508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1s8dqy5 e90swyx2&quot;]/div[@class=&quot;css-1brt7yz&quot;]/div[@class=&quot;css-1i12xq8&quot;]/i[@class=&quot;css-15kuy91&quot;]</value>
      <webElementGuid>b6ef28d4-f15e-4c6c-8d72-2200ec9c5cdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div[3]/div/i</value>
      <webElementGuid>382f2cec-c733-4532-9a9e-f16c29896e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/i</value>
      <webElementGuid>86ec8926-cb52-4656-9da9-259eed402b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
